### ISSUE TITLE
Text should be stored by default.

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#102]
It appears the default settings are leading to the text being sent straight to `text` for indexing rather than going via `content` and getting stored.

**Comment by anjackson** [comment]
Hm, seems to be setting the default behaviour correctly. Not sure how to reproduce this.

**Comment by anjackson** [comment]
@thomasegense I'm having trouble reproducing this issue. Have you got this property set to `false` somehow?

https://github.com/ukwa/webarchive-discovery/blob/master/warc-indexer/src/main/resources/reference.conf#L16

**Comment by thomasegense** [comment]
It was a config property as you said:
   # Should we index the content body text?
                    "text" : true,

The  config file I used was one found in the project (there are several config files, also for unit-test) and it was not enable for this.
 So the real confusion is which config is the suggested default config file to be used in a project (and not from the unittests)

**Comment by thomasegense** [comment]
You can just close the issue.

**Comment by anjackson** [comment]
Okay, thanks @thomasegense and sorry for the bother. The top-level `configs` folder contains configurations we use in anger.

I'm not really happy with the configuration mechanism, but I'm not sure what else to replace it with.
