### ISSUE TITLE
Config, restrict HTTP response codes as regexp

### ISSUE THREAD

**Issue by thomasegense** [ukwa/webarchive-discovery#108]
Current code (conf file):
    # works by matches starting with the characters, so "2" will match 2xx:
                "response_include" : [
                    "2"
                ],

I suggest using a regexp expressions instead of a "startsWith". We are interested in 404, and probably others as well, to see when the webpage was down.

**Comment by anjackson** [comment]
Yes, we can switch to a regex if that makes things easier. However, the current system does already allow a list to be passed in, and so you could do this kind of thing instead:

```
"response_include" : [
"2", 
"404"
],
```

**Comment by thomasegense** [comment]
That does solve to the current situation for us. I will close the issue.
