### ISSUE TITLE
url_path to text field instead of url

### ISSUE THREAD

**Issue by thomasegense** [ukwa/webarchive-discovery#109]
Instead of :     `<copyField source="url" dest="text"/>`
We could prefer:  `<copyField source="url_path" dest="text"/>`

This is to avoid having http and domain in this field (redundant).
Data example from our index:
` "url_path":"/Li/Vejledning/Images/Masseoprettelser2.gif"}`
` "url":"http://www.rismoelleskolen.dk/Li/Vejledning/Images/Masseoprettelser2.gif"`,

so http, www,rismoelleskolen, dk would not go into the default text search field.

**Comment by tokee** [comment]
After pull request #135 this is no longer relevant: `url_search` does the job better than `text`.

When #134 is closed (we're working on that locally), both `url_search` and `text` will be used for search and the `copyField` from `url to `text` will be removed.
