### ISSUE TITLE
Should URL-normaliser normalise HTTP/HTTPS?

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#117]
It seems that the normalisation/canonicalisation of `url_norm`sees `http://example.com` and `https://example.com` as two different URLs. The common case seem to be that there is no difference between the content behind the two protocols, so shouldn't the canonicaliser convert `https://` to `http://`?

**Comment by anjackson** [comment]
Yes, that's what we usually do elsewhere, so I think that should certainly be the default at least.
