### ISSUE TITLE
Test failing following new URL normalisation

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#136]
Hi @tokee following #133 I'm seeing a test failure:

```
  HtmlFeatureParserTest.testNormalise:109 Normalisation of 'http://example.org' expected:<http://example.org[]> but was:<http://example.org[/]>
```

I assume I'm fine to just fix the test to adopt the new normalisation scheme?

**Comment by tokee** [comment]
As part of the unified normalisation, @thomasegense has encountered a number of problems (warnings, really). I'll create an issue for it and fix this issue while I work on it.

**Comment by tokee** [comment]
I am a bit in doubt about the correct thing to do here. The normaliser ensures that domain-level URLs always ends in `/`, which is the RFC-compliant way to represent such links. With that in mind, the normalisation is correct and the test should be changed. We don't have to follow RFCs for the Solr normalisation though. Unless we discover a reason to explicitly state the trailing `/`, it is just a wasted byte to us.

With that in mind, we might also consider remove the heading `http://` as all our `url_norm`-entries has that exact header. I don't support that though, as we might at some point add Gopher, FTP and other material.

**Comment by anjackson** [comment]
I'm happy with the new normalisation and leaving the scheme in. Inconsistency in handling trailing slashes has caused me problems before, and the main thing is that it's done consistently. Sticking to the RFC makes it easier to remember which way around it is!

**Comment by tokee** [comment]
Great. Since pull #140 enforces trailing slash on domain-links, I consider this closed.
