### ISSUE TITLE
Inconsistency crawl_date/crawl_year

### ISSUE THREAD

**Issue by bnfleb** [ukwa/webarchive-discovery#142]
warc-indexer use `java.util.Calendar` to extract `crawl_year` from the `crawl_date` but the calendar has no timezone set. So for a server with a different timezone than UTC, there is an inconsistency between  `crawl_year` and `crawl_date`.
For example :
```
"crawl_date":"2016-12-31T23:00:03Z",
"crawl_year":"2017",
```
Wouldn't it be better to set the calendar like this?
```
private final Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
```

Another question, there is a `crawl_year_month` field and a `crawl_year_month_day` field in the schema. Are they filled by warc-indexer ?

**Comment by anjackson** [comment]
Oops. Good catch.

**Comment by tokee** [comment]
Ah well, I was preparing a pull request. Nevermind now, ignore the commit thet GitHub mentions above.

**Comment by anjackson** [comment]
Oops, sorry! Thanks though!

**Comment by tokee** [comment]
Nothing to be sorry about. I should have assigned it to myself before I fixed it.

**Comment by anjackson** [comment]
As should I! :-)
