### ISSUE TITLE
Time limiting for analysers causes the JVM to hang

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#149]
In order to bypass the Halting Problem, multiple analysers in `warc-indexer` creates a Runnable with the job, wraps it in a `Thread` and waits for the `Thread` to finish with a timeout. If it does not finish, an interrupt is called. 

The problem with this approach is that interrupts are not guaranteed to terminate Threads, so there can be running Threads when overall processing of the WARC files has finished. This can block the indexer from finishing as the JVM waits for the Threads.

The solution is to make all Threads daemons, which tells the JVM that it does not have to wait for them on exit.

**Comment by anjackson** [comment]
I believe this is resolved now. Please re-open if not.
