### ISSUE TITLE
Clean up indentation in the code?

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#173]
As far as I can infer, the code base is intended to be indented with tabs.

Running `find . -iname "*.java" -exec bash -c "echo -n {}\ tab-lines:\  ; grep -v ^[\ $'\t'][^*]*[*] < {} | grep -c ^$'\t' | tr -d '\n' ; echo -n "/" ; grep ^[\ $'\t'] < {} | grep -v ^[\ $'\t'][^*]*[*] | wc -l" \;` gives a list of all the files with tab-indented lines vs. all indented lines (that are not JavaDoc). Hacking a bit more, we get the stats

- Total Java files: 175
- Consistently tab-indented: 56
- Consistently space-indented: 45
- Mix of tab and space: 74

Should we do something about this mess? And if we do, how do we avoid the mess in the future?

**Comment by anjackson** [comment]
I should install the Maven plugin that forces a single style (CheckStyle?!) and fix it in one big change.

**Comment by anjackson** [comment]
Four Spaces FTW.

**Comment by anjackson** [comment]
Hm, looks like CheckStyle can be used to validate but not fix. There are auto-formatters that use the Eclipse formatting engine [e.g.](https://code.revelc.net/formatter-maven-plugin/examples.html) but they are likely to aggressive.

I should be able to do the tabs-to-spaces conversion manually as a one-off.

**Comment by anjackson** [comment]
Nasty, brutish but short:

    find . -type f -name *.java -exec perl -pi -e 's,\t,    ,g' {} \;
