### ISSUE TITLE
url_type:splashpage is problematic

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#239]
The check for setting `url_type:splashpage` is found in `WARCIndexer` as
```
        if (url.getPath().equals("/") || url.getPath().equals("")
                || url.getPath().matches("/index\\.[a-z]+$")) {
            solr.setField(SolrFields.SOLR_URL_TYPE,
                    SolrFields.SOLR_URL_TYPE_SLASHPAGE);
```
The problem (or maybe "intentional decision"?) here is that the path of the URL does not include arguments, so a query for `url_type:splashpage` will result in URLs such as
```
http://www.example.com/?attachment_id=483
https://example.com/?tags=tag:hele_sagen.example.com,2011:10_id%C3%A9er_der
https://www.example.com/?ai1ec_event=ikke-aabenhal
https://example.com/?tag=windows
https://example.com/index.php?route=common/home
http://example.com/index.php?c=103
```
A lot of these does not look like landing pages (which I guess "slashpages" are supposed to be). Maybe we can add a new type `landingpage` or something like that, that is only assigned if there are no arguments?

**Comment by anjackson** [comment]
See #213 :-)

**Comment by tokee** [comment]
Dóh!
