### ISSUE TITLE
Store the SURT

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/webarchive-discovery#28]
We've already discussed using the PathHierarchyTokenizerFactory to manage the Subject hierarchy. Similarly, we could store the SURT in addtion to (instead of?) the host and use said tokenizer (splitting on ",") to enable us to search via host hierarchy (i.e., "uk", "co.uk", "bbc.co.uk", etc).

**Comment by anjackson** [comment]
Superseded by #81
