### ISSUE TITLE
Switch to docValues for almost everything.

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#51]
When running in the 2B documents range, even facets with moderate cardinality (e.g. hundreds or thousands of values) cause OOM errors if you try to add them as facets. (e.g. author, content_type, etc.). The workaround is to use the facet.enum method rather than the fc/fcs, but using docValues is more performant. This also applies to the crawl_date(s) fields, which should work quicker if they are set up as docValues.

I expect this means that indexes will not be compatible, so I'm pushing this off to the 2.2.0 release.

**Comment by tokee** [comment]
Indexes are actually compatible, but documents indexed without DocValues will not be present in the facet result, when the field is marked as having DocValues in the schema. So yes, a full re-index is the way to go.

**Comment by anjackson** [comment]
Okay, just committed the main changes on the 2.2 dev branch (ukwa/webarchive-discovery@f6602d3)
