### ISSUE TITLE
PDFTextStripper.properties must be specified

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#53]
A test-run gave 400 lines of 
```
ERROR TikaExtractor:429 - ParseRunner.run() Exception: IOException: Error: could not find resource 'org/apache/pdfbox/resources/PDFTextStripper.properties' on classpath.
```
I know nothing about how a sane PDFTextStripper.properties looks, but hopefully there is a default one somewhere that can be added?

**Comment by anjackson** [comment]
That sounds like mixed-up jars. Do we have two versions of PDFBox on the classpath?

**Comment by tokee** [comment]
`mvn dependency:tree` to the rescue: `warc-indexer` and `warc-hadoop-indexer` uses PDFBox 1.8.6, while `digipress-tika` uses 1.8.8.

With multi-module maven, it it possible to define dependencies with versions in the super-pom and then add the dependencies in the modules without the versions, thus ensuring consistency.

**Comment by anjackson** [comment]
Unfortunately, I don't think that would work. It would fix pdfbox only, not the parent 'preflight' dependency, that also needs to be updated to the latest version. i.e. the pdfbox version dependency is hidden by the 'tika' and 'preflight' parent dependencies.

Or is there a clever way to deal with that case?

**Comment by tokee** [comment]
In another project we handled it by setting exclusions on the components including other versions of sub-components:
```
<include>foo 1.2</include>
<include>framework 2.5
  <exclude>foo 1.1</exclude>
</include>
```
Of course that only works when the upper levels are compatible with the lower ones,

**Comment by anjackson** [comment]
Which, in this case, they are not. :-/

**Comment by tokee** [comment]
Bugger then. Until we have versioned imports in Java, I don't know what to do.

**Comment by anjackson** [comment]
I guess we'll have to keep an eye on it manually for now.
