### ISSUE TITLE
Test resources should be resolved with the classloader

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#54]
A common pattern for the tests in the project is the resolving of resources with `new File("src/test/resources/myresource.dat")`, which assumes that the current folder for the JVM is at a specific place in the tree. This is not always true and my IDEA setup does not do this, causing a lot of the unit tests to fail due to FileNotFoundExceptions.

One fix is to use the class-loader to resolve the files as described on http://devblog.virtage.com/2013/07/how-to-get-file-resource-from-maven-srctestresources-folder-in-junit-test/ or to introduce a utility method that tries to resolve resource in multiple days.

**Comment by anjackson** [comment]
Well, that's a surprised. I was under the impression that the CWD being set was part of the standardised (Maven) build process. I guess not!

Unfortunately, in some of the test cases, it really does need to be a file rather than and InputStream. I guess I'll have to pop the files to a temp folder in those cases.

**Comment by tokee** [comment]
The class loader can deliver a File if needed. See https://github.com/netarchivesuite/webarchive-discovery/blob/sb-2-dev/warc-indexer/src/test/java/uk/bl/wa/analyser/payload/HTMLAnalyserTest.java or https://github.com/netarchivesuite/webarchive-discovery/blob/sb-2-dev/warc-indexer/src/main/java/uk/bl/wa/analyser/text/lang/LanguageIdentifier.java#L123 for examples of resolving.

**Comment by anjackson** [comment]
For whatever reason, this started to cause a problem with the build, so I've had to switch to loading things in this way. I think I've caught them all - please re-open if I've missed some.
