### ISSUE TITLE
Add support for an indexing exclusion list.

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#7]
Add support for a Wayback-style indexing inclusion list. This should work with to the functionality in #3, but matching URLs are dropped at the indexing stage. i.e. WARCIndexer drops them.

**Comment by PsypherPunk** [comment]
Re-opened as per discussions; needs documentation.

I _think_ this is implemented [here](https://github.com/ukwa/webarchive-discovery/blob/022c3cd46e56e5e6258174d41bfb9c08c350d199/warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java#L175).

**Comment by anjackson** [comment]
https://github.com/ukwa/webarchive-discovery/wiki/Excluding-Resources-From-Indexing
