### ISSUE TITLE
extract EXIF  data from images

### ISSUE THREAD

**Issue by thomasegense** [ukwa/webarchive-discovery#70]
And create new field in schema for these.

**Comment by anjackson** [comment]
FWIW, I think Tika extracts EXIF, but probably doesn't keep it separate from the rest. The ```extract_all_metadata``` flag puts all the metadata Tika finds into the ```content_metadata``` field.

https://github.com/ukwa/webarchive-discovery/blob/master/configs/jisc6.conf#L110

**Comment by thomasegense** [comment]
We have not enabled it sorry. But we are thinking about promoting it to several fields (dynamic  field exif_* etc.) Consider this closed

**Comment by thomasegense** [comment]
I enabled the tika.extract_all_metadata option and the index'er failed due to content_metadata is not multivalued. But this is not an problem since we will not use all these metadata.
But I am considering a special field for image-date and image-pos from EXIF data.
