### ISSUE TITLE
Better analyzer on url_norm field

### ISSUE THREAD

**Issue by thomasegense** [ukwa/webarchive-discovery#71]
More characters need to be removed when analyzing this field. Often the url has many relevant 
terms for a search.
Example www.xxx.dk/omaba.jpg

Since . (dot) is kept and not made into a white space, a search for omaba will not match this image.

**Comment by anjackson** [comment]
I thought the idea of url_norm was to provide exact matches?

**Comment by thomasegense** [comment]
Again you are correct. We will need a new field again for analyzed url field. Searching in URLS (for our image search etc.) is important.

**Comment by thomasegense** [comment]
I will try work on this problem on our branch and a solution will be a merge request.
