### ISSUE TITLE
Add domain_surt, url_path and status_code fields

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#81]
Add these new fields,

* `domain_surt`: Like `host` but as a SURT, storing all the levels. e.g. `'news.bbc.co.uk'` becomes
`['(uk,', '(uk,co,', '(uk,co,bbc,)', '(uk,co,bbc,news)']`. (see #28)
* `links_domains_surts`: Like links_hosts, but as all the levels of a SURT.
* `url_path`: Just the path part of a URL, allowing queries like `url_path:/news/* AND domain_surt:(uk,co,bbc*)`
* `status_code`: Just the HTTP response status code (and we'll attempt indexing all responses -- not just 200).

n.b. also I need to check that http status code filtering can be managed/disabled.

**Comment by tokee** [comment]
SURT has obvious advantages over non-SURT (and really should have been the way to write URLs in general). Is there any reason to have non-SURT fields for `host`, `domain`, `links_hosts` and `links_domains` at all? I seems like wasted space to me. All tools and GUIs interacting with the index could (easily) map to and from SURT, hiding that implementation detail when its nature is not relevant.

Technically this is possible to do on the Solr level, but it is probably not a good idea to introduce a custom extension to Solr. http://lucene.apache.org/solr/6_5_1/solr-core/org/apache/solr/schema/FieldType.html

**Comment by anjackson** [comment]
I'm wary of immediately dropping/changing those fields, as that would be a breaking change that might cause problems for others.

Maybe we could make SURT-ordering for `hosts/domains/links_hosts/links_domains` optional?

I don't know if this would save much space though, as the proposed separate `domain_surt` field would be multivalued, allowing e.g. facet on TLD. This would still be a separate field from the `host` and from the `domain` which would be used to specify the private suffix. i.e. we'd still need all the separate fields for separate purposes, I think.

**Comment by GilHoggarth** [comment]
We're getting there with this but I notice that 'domain_surt' are not being added correctly. See http://dev-solr4:8983/solr/newSchemaTest/select?fl=url,%20url_path,%20status_code,%20type,%20domain_surt,%20links_domains_surts,%20links_domains&indent=on&q=-id:sha*&wt=json
From the first record: 
"domain_surt":["{add=(uk,}",
          "{add=(uk,gov,}",
          "{add=(uk,gov,wales,}"],

**Comment by chrispeacockbl** [comment]
OK, it was a one-liner (hopefully) but the reason I didn't pick up on this was because my unit test wasn't doing what it was supposed to....

How shall we do this with regard to pull requests? It's in the issue81 branch but there's that matter of including issue 82.

**Comment by GilHoggarth** [comment]
From his master's voice, can you merge the code fix into each branch - issue 81, issue-81+issue-82, issue-81+issue-82-j7.

**Comment by chrispeacockbl** [comment]
@GilHoggarth Done.

**Comment by anjackson** [comment]
I realised I got the naming convention wrong here, and updated it accordingly. As the surts are based of the full host (not just the private name/domain part), they should have been `host_surt` and `links_hosts_surts.

**Comment by anjackson** [comment]
On your point @tokee I'm going to leave the non-SURT forms in for now, but they should be considered deprecated and will be dropped in a future release.
