### ISSUE TITLE
Add a type field that covers high-level type

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#82]
This field will supersede `content_type_norm` and it intended to be interoperable with the field of the same name in the Collections & Targets index. The idea is that we should be able to merge search results from both systems and provide a single facet for 'item type'.

For URLs, the `type` should be one of:

- Web Page (i.e. HTML)
- Document (i.e. DOC, PDF...)
- Image
- Audio
- Video
- Data (i.e. Spreadsheet, Excel, CSV...)
- Presentation (i.e. Powerpoint or similar)
- Other

The `content_type_norm` is  slightly finer-grained, e.g. Word, PDF, Powerpoint, Excel are separate types of Document.

**Comment by anjackson** [comment]
This looks good, except there should be no default for the new type field.

```
<field name="type" type="string" indexed="true" docValues="true" multiValued="false" default="Other"/>
```

Should just be

```
<field name="type" type="string" indexed="true" docValues="true" multiValued="false"/>
```

**Comment by GilHoggarth** [comment]
Grand. Will push this into repo in a moment...

**Comment by chrispeacockbl** [comment]
Thanks @GilHoggarth .

**Comment by chrispeacockbl** [comment]
...And @anjackson !

**Comment by anjackson** [comment]
@GilHoggarth notes that the `other` category in `content_type_norm` is significantly larger than for `type:Other` - are records going unclassified?

**Comment by chrispeacockbl** [comment]
I'm not sure how that could be; I'm setting the type in all the places that content_type_norm is set, as far as I can see.

What are 'content_type' and 'content_type_full' in these instances?

**Comment by anjackson** [comment]
Can you or @GilHoggarth run a query along the lines of `-type:["" TO *]` to look at the records with no `type`?

**Comment by GilHoggarth** [comment]
Running http://devsolr-proxy:8983/solr/newSchemaTest/select?facet.field=type&facet.query=type:[%22%22%20TO%20*]&facet=on&indent=on&q=*:*&rows=0&wt=json gives
"response":{"numFound":129670,"start":0,"docs":[]
  },
  "facet_counts":{
    "facet_queries":{
      "type:[\"\" TO *]":77811},
    "facet_fields":{
      "type":[
        "Web Page",44772,
        "Other",19069,
        "Image",13417,
        "Document",551,
        "Audio",2]},

whereas http://devsolr-proxy:8983/solr/newSchemaTest/select?facet.field=content_type_norm&facet.query=content_type_norm:[%22%22%20TO%20*]&facet=on&indent=on&q=*:*&rows=0&wt=json gives
"response":{"numFound":129670,"start":0,"docs":[]
  },
  "facet_counts":{
    "facet_queries":{
      "content_type_norm:[\"\" TO *]":129670},
    "facet_fields":{
      "content_type_norm":[
        "other",70928,
        "html",44772,
        "image",13417,
        "text",551,
        "audio",2]},

**Comment by GilHoggarth** [comment]
129670 - 77811 = 51859
19069 + 51859 = 70928
Obvs.

**Comment by chrispeacockbl** [comment]
Could this be because of field defaults? I.e. the existing `content_type_norm` field has a default:

`<field name="content_type_norm" type="string" indexed="true" docValues="true" multiValued="false" default="**other**"/>`

However, the new `type` field should not as per @anjackson's comment above. Could there be records created that have not gone through the process of having the `content_type_norm` field set by the indexer, i.e. have been inserted into the Solr index by some means which bypasses that (and hence the code that populates the new `type` field)?

**Comment by anjackson** [comment]
The gap appears to be down to revisit records. As we do not have a good pattern for re-inflating revisit records, I suggest we modify the indexer configuration file to ignore them for now.
