### ISSUE TITLE
hash should be single-valued

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#95]
Currently the schema defines `hash` is multi-valued. This makes it unusable for [grouping](https://lucene.apache.org/solr/guide/6_6/result-grouping.html) and - less importantly - has a slight space+performance overhead.

Setting the `hash`-field to single-valued implies that each document in the Solr index represents only one unique instance of a resource. This is not compatible with the "track the life-cycle of a resource by updating the document"-approach. If that is toe be supported, I suggest adding a new field: `hashes`.

**Comment by anjackson** [comment]
The idea was to support lookup via multiple hashes, but I didn't realise this would prevent grouping. It makes sense to have `hash` and `hashes` to me.

**Comment by anjackson** [comment]
This breaking change should be noted somewhere!
