### ISSUE TITLE
Why are year and years strings?

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#97]
In general, the Solr schema should define its value as narrow as possible, for space & speed. As far as I can see in `Times.java`, year will _always_ be 4 digits, so specifying the `year` and `years`-fields as integers seems the way to go.

**Comment by tokee** [comment]
Same goes for `crawl_year_month_day` and `crawl_year_month`.

**Comment by anjackson** [comment]
This is largely an historical artefact of me just treating useful faces as opaque strings and not worrying about overheads. Makes sense to tighten them up now.

Thanks for all these suggestions @tokee  - much appreciated.
