### ISSUE TITLE
Multiple schema suggestions

### ISSUE THREAD

**Issue by tokee** [ukwa/webarchive-discovery#98]
* `image_size` is int, but should be long: There are 2BPixel+ images in the wild.
* Some attributes uses single-quotes while others use double-quotes. Please use same quoting for all attributes.
* `id` should have docValues enabled: Paging with cursorMark, which is both usable for deep paging and exports, need a unique and docValued field - `id` is the obvious candidate. This is not an essential requirement for export as newer Solr has streaming exports, which largely supersedes cursorMark.
* `url`, `url_norm` and `referer_url` are both stored and docValued. Is this on purpose? They do take up space and since docValues can be returned as part of the document result, storing small string fields seems a bit superfluous.  Also, they should be `multiValued="false"`
* `wayback_date` is String. Is it unreliable data, since it is not defined as a real date?
* `content_length` should have docValues, with the use case being lower-overhead (range|interval) faceting. Also consider it for `content_text_length` and `crawl_date` for the same reason.

**Comment by anjackson** [comment]
I guess I asked for that... ;-)

**Comment by anjackson** [comment]
`id` can be `stored=false` one `docValues=true`, right?

**Comment by tokee** [comment]
Kindasortanearly. [SOLR-8740](https://issues.apache.org/jira/browse/SOLR-8740) discusses it quite well. My takeaway is that docValues does not retain ordering and that they are not well suited for large blocks of content. For most fields in webarchive-discovery this does not seem to be an issue, so my default (when enabling docValues) would be `stored="false" docValues="true"`.

[Elasticsearch enables docValues per default](https://www.elastic.co/guide/en/elasticsearch/reference/current/doc-values.html) but [does not store them](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-store.html). It is not directly comparable to Solr though, as they seem to store the original index-document as part of each record, or something to that effect.

**Comment by anjackson** [comment]
Thanks. I think I've made the appropriate changes. The only remaining issue is the `wayback_date`, which I guess should be a `long` rather than a string?

Storing the dates as `int/long` in this way does make me slightly uncomfortable, but not really for any good reason beyond that a date that is a `int/long` might be expected to be a UNIX timestamp rather than a weird composite pseudo-number.

**Comment by anjackson** [comment]
Could you check if you think I've done the right things, @tokee? If so I think we can close this.

**Comment by tokee** [comment]
I might be misunderstanding the purpose of the `wayback_date`. Why not store it as a Solr date so that it renders properly and one can do date-math on it?

**Comment by anjackson** [comment]
Ah, so, the primary purpose of the `wayback_date` is to be used to construct a Wayback URL, e.g. the `20160107112805` in `https://www.webarchive.org.uk/wayback/archive/20160107112805/http://www.bl.uk/`

The `crawl_date` is the same as the `wayback_date` but stored as a date for doing date maths. We don't really need `wayback_date` if the client is happy to do the reformatting, but for simple clients it's simpler to just have it in there.

Hm, so, in which case, it could just be stored and not indexed. Perhaps that's a better idea?

**Comment by anjackson** [comment]
Lets say yes.
